### ISSUE TITLE
Is there a tutorial to use this template in production mode?

### ISSUE THREAD

**Issue by alirayaneh** [who-jonson/sakai-nuxt#124]
Hello, have a good day

Is there a tutorial to use this template in production mode?
Or how should we use this template in a project?

For example, I'm going to start a project using Nuxtjs 3  and Laravel 9.
How should I use this bundle in a fresh version of Nuxt js in my project?

**Comment by who-jonson** [comment]
You may consider this project as a fresh laravel project with predefined layout from Primevue

**Comment by who-jonson** [comment]
You may consider this project as a fresh nuxt 3 project with predefined layout from Primevue
