### ISSUE TITLE
Unable to Run the Template

### ISSUE THREAD

**Issue by mark033100** [who-jonson/sakai-nuxt#186]
Greetings, so I just cloned it and finished doing npm install, aside from deprecated warnings, the installation finished. But when I tried to run it using npm run dev I got this error.
![image](https://github.com/user-attachments/assets/eca4b3e5-0418-44ca-afe6-2b1d26f2da51)

**Comment by who-jonson** [comment]
Couldn't reproduce the issue. 

Check here: [Stackblitz](https://stackblitz.com/~/github.com/who-jonson/sakai-nuxt)
