### ISSUE TITLE
Unable to build project because of chart.js module not found

### ISSUE THREAD

**Issue by jonorn82** [who-jonson/sakai-nuxt#72]
I can run `npm install` and `npm run dev` without issues but when I try to build the project, `npm run build`, I get the following error:

> Error: Cannot find module chart.js/auto imported from file:///C:/Users/username/forritun/sakai-nuxt/node_modules, file:///C:/Users/username/forritun/sakai-nuxt/node_modules/nuxt/node_modules, file:///C:/Users/username/forritun/sakai-nuxt/node_modules/nitropack/node_modules, file:///C:/Users/username/forritun/sakai-nuxt/, file:///C:/Users/username/forritun/sakai-nuxt/node_modules/_index.js, file:///C:/Users/username/forritun/sakai-nuxt/node_modules, file:///C:/Users/username/forritun/sakai-nuxt/node_modules/nuxt/, file:///C:/Users/username/forritun/sakai-nuxt/node_modules/nuxt/node_modules/_index.js, file:///C:/Users/username/forritun/sakai-nuxt/node_modules/nuxt/node_modules, file:///C:/Users/username/forritun/sakai-nuxt/node_modules/nitropack/, file:///C:/Users/username/forritun/sakai-nuxt/node_modules/nitropack/node_modules/_index.js, file:///C:/Users/username/forritun/sakai-nuxt/node_modules/nitropack/node_modules

I tried both nodejs v14 and v16
The chart.js folder is in the node_modules folder
Any Idea what is causing this?

**Comment by ahalsu67** [comment]
Hi @jonorn82,
Try adding `'chart.js'` into the `build.transpile `array just below `'primevue'` inside `nuxt.config.tx` file.
